### ISSUE TITLE
Unable to build project after updating SpecFlow.Actions.WindowsAppDriver to v0.1.341

### ISSUE THREAD

**Issue by DrunkenDeveloper** [SpecFlowOSS/SpecFlow.Actions#103]
Hi,

I've updated `SpecFlow.Actions.WindowsAppDriver` to the recent version 0.1.341.
Unfortunately, the project won't build any more. During the restore, it tries to resolve `SpecFlow.Actions.Appium` and `SpecFlow.Actions.Configuration.SpecFlowPlugin` (deprecated)  in version >= 0.1.341, but can only find version 0.1.177.

Maybe I'm missing something here or need these packages to be rebuilt to match the version of `SpecFlow.Actions.WindowsAppDriver`?

Best regards

**Comment by SabotageAndi** [comment]
Ah, ok there is a bug in the ci/cd pipeline. I will fix it next week.

**Comment by SabotageAndi** [comment]
CI/CD pipeline is fixed and correct packages should now be on NuGet.org.
