### ISSUE TITLE
Browserstack Build Names

### ISSUE THREAD

**Issue by jasonright** [SpecFlowOSS/SpecFlow.Actions#104]
Hi Guys,

We've got a pretty simple problem as all of our tests are going into one build called Chrome.Windows for example and this obviously make's it very tedious and complicated when looking through the tests. Is there any way to a pass an option or string parameter to the build name so it includes the date for example or something so we can split these builds up better?

Thanks a lot for the great package.

**Comment by SabotageAndi** [comment]
Fixed with 0.1.344
