### ISSUE TITLE
Keyboard actions in Specflow.actions.playwright

### ISSUE THREAD

**Issue by ibrahimuye** [SpecFlowOSS/SpecFlow.Actions#112]
I use the below standard playwright way to hit the enter button after filling the text box, but I could not a way to use Keyboard in Specflow.actions.playwright

//this works
await _addressInput.FillAsync("21 Pacific St, Pittsfield, MA");
await _page.Keyboard.PressAsync("Enter");

I need to find how to use Keyboard in Specflow.actions.playwright

**Comment by SabotageAndi** [comment]
There is no difference. Get your page object and call the APIs. 
You don't have to use the `Interactions` class.

**Comment by ibrahimuye** [comment]
thank you
It worked like that
await _page.Result.Keyboard.DownAsync("ArrowDown");
