### ISSUE TITLE
[Excel] Create Excel code snippets

### ISSUE THREAD

**Issue by JordanWestern** [SpecFlowOSS/SpecFlow.Actions#21]
1. Create Excel code snippets

**Comment by JordanWestern** [comment]
@SabotageAndi need some discussions on this one.

Have found this info https://coderwall.com/p/app3ya/read-excel-file-in-c but this is not working in .net core, only framework 4.X+ and .net5

**Comment by SabotageAndi** [comment]
Please have a look at [ClosedXml](https://github.com/closedxml/closedxml). I am using this lib since years for working with Excel files.
