### ISSUE TITLE
Specflow.Action.Selenium doesn't always dispose chromedriver.exe processes

### ISSUE THREAD

**Issue by DomZZ** [SpecFlowOSS/SpecFlow.Actions#30]
I was in a webinar where I asked that if Specflow.Action.Selenium gracefully dispose chromedriver and chrome instances when I cancel test execution.

And the guy told me : Yes !

but I have implemented Specflow.Action.Selenium nuget and I can tell you that this is not the case at all (at least with Nunit runner).

For sure Dispose methods are not called when cancelling tests,  may be this is different with Specflow Runner ...

**Comment by JordanWestern** [comment]
Hi @DomZZ ,

That guy was me and you're totally right, I apologise for the misinformation. In any runner the behavior will be the same as of course dispose will never get executed.
