### ISSUE TITLE
[Question] Instances lifetime

### ISSUE THREAD

**Issue by DomZZ** [SpecFlowOSS/SpecFlow.Actions#31]
Hi,

I drop my custom code to use SpecFlow.Actions.Selenium but I'm having some questions about the lifetime on instanciated objects :
- BrowserDriver
- BrowserDriver.Current

Also can you give me the same answer for SpecflowOutputDriver and all other injected objects if possible

**Comment by JordanWestern** [comment]
Hi @DomZZ ,

You can see the implementation of the driver in this project - https://github.com/SpecFlowOSS/SpecFlow.Actions/tree/main/Plugins/SpecFlow.Actions.Selenium

I am not familiar with SpecflowOutputDriver but again you will find it in the repo somewhere

**Comment by SabotageAndi** [comment]
BrowserDriver and the WebDriver have the lifetime of the Scenario.

`ISpecFlowOutputHelper` has a lifetime of the test thread.

You can find a not complete overview which class is registered in which container here: https://docs.specflow.org/projects/specflow/en/latest/Extend/Available-Containers-%26-Registrations.html
