### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by mihben** [SpecFlowOSS/SpecFlow.Actions#46]
Hi,

Thanks for the package, it is very useful.  I would ask an improvment.
Is it possible to extend the `specflow.actions.json` with the `SlowMo` parameter? 

https://playwright.dev/dotnet/docs/api/class-browsertype/#browser-type-launch

**Comment by kapros** [comment]
@mihben hello, the requested change was added and is already available with the latest version of the package.
