### ISSUE TITLE
[Feature request] : specflow.actions.json documentation

### ISSUE THREAD

**Issue by DomZZ** [SpecFlowOSS/SpecFlow.Actions#54]
I didn't find a place where this file is documented. Did I miss something ?
I am trying to use Selenium Grid 4 with Specflow.Actions.Selenium.

**Comment by seanrand57** [comment]
@DomZZ is a configuration example of Specflow.Actions.Selenium under the _**Configuration**_ section in the readme file.  This should be detailed enough for examples to build upon as it demonstrates the nesting and json structure that can accommodate capabilities and timeouts.

https://github.com/SpecFlowOSS/SpecFlow.Actions/tree/main/Plugins/SpecFlow.Actions.Selenium

**Comment by DomZZ** [comment]
thanks @seanrand57 , I tough there was more properties.
