### ISSUE TITLE
SpecFlow.Actions.Browserstack Samsung Browser Driver

### ISSUE THREAD

**Issue by tomrobinsonv** [SpecFlowOSS/SpecFlow.Actions#90]
Is it possible to get support for Samsung Browsers with Browserstack?

**Comment by SabotageAndi** [comment]
@tomrobinsonv can you point me to some documentation for it? Then I can answer your question.

**Comment by tomrobinsonv** [comment]
I can't find many docs specifically for samsung browsers but when connecting to browserstack manually, it seems the only difference is the browser capability value being 'samsung' instead of 'chrome' or 'safari'. I'd imagine a json config file for it would look something like this?
`{
  "selenium": {
    "defaultTimeout": 15,
    "pollingInterval": 5,
    "browser": "Samsung",
    "capabilities": {
      "os_version": "10.0",
      "device": "Samsung Galaxy S20",
      "real_mobile": true,
    },
    "browserstack": {
      "url": "https://hub-cloud.browserstack.com/wd/hub/"
    }

  }
}`

**Comment by tomrobinsonv** [comment]
A bit old now, but it appears it's possible to open the Samsung browser using a chrome driver if you can add experimental options to the driver on initialisation. Could I pass these options in the capabilities object?

https://medium.com/samsung-internet-dev/how-to-use-webdriver-and-chromedriver-to-automate-samsung-internet-e1249814823e

**Comment by SabotageAndi** [comment]
Ok, the info with the browser capability helps.
I need to think a little bit about how to add this. 🤔

**Comment by mrampass** [comment]
@tomrobinsonv I have not tried it myself, but by looking at the BrowserStack documentation,below config should work with the existing implementation for chrome?

{
  "selenium": {
    "defaultTimeout": 15,
    "pollingInterval": 5,
    "browser": "chrome",
    "capabilities": {
      "device":"Samsung Galaxy S20",
      "os_version": "10",
      "real_mobile": true,
      "browser":"samsung",
      "build": "Example"
    },

**Code from BrowserStack capability  generator** 
ChromeOptions capability = new ChromeOptions();
capability.AddAdditionalCapability("os_version", "10.0", true);
capability.AddAdditionalCapability("device", "Samsung Galaxy S20", true);
capability.AddAdditionalCapability("real_mobile", "true", true);
capability.AddAdditionalCapability("browserstack.local", "false", true);
capability.AddAdditionalCapability("browser", "samsung", true);

**Comment by mrampass** [comment]
Have tested the below config and it works against latest version of specflow.actions.browserstack code
{
  "selenium": {
    "browser": "chrome",
    "capabilities": {
      "device": "Samsung Galaxy S20",
      "os_version": "10",
      "real_mobile": true,
      "browser": "samsung",
      "browserstack.user": "",
      "browserstack.key": ""
    }  
  }
}

**Comment by SabotageAndi** [comment]
Awesome @mrampass!
