### ISSUE TITLE
Using full list of Playwright supported browsers 

### ISSUE THREAD

**Issue by AptecoJoe** [SpecFlowOSS/SpecFlow.Actions#96]
Is it possible to use specflow with the full list of playwright browsers (desktop and mobile). I have been able with playwright out the box but recently switched to using specflow but couldn't find how?

If not, is it planned to be supported?

**Comment by SabotageAndi** [comment]
Ah, we didn't notice that there is now Safari and Opera support in Playwright.

Adding a new browser isn't hard. The main stuff is here: https://github.com/SpecFlowOSS/SpecFlow.Actions/blob/main/Plugins/SpecFlow.Actions.Playwright/SpecFlow.Actions.Playwright/DriverInitialiser.cs

- add new enum value at https://github.com/SpecFlowOSS/SpecFlow.Actions/blob/main/Plugins/SpecFlow.Actions.Playwright/SpecFlow.Actions.Playwright/Browser.cs
- Copy a Get*DriverAsync Method 
- make sure that it is called https://github.com/SpecFlowOSS/SpecFlow.Actions/blob/main/Plugins/SpecFlow.Actions.Playwright/SpecFlow.Actions.Playwright/BrowserDriver.cs#L35

I am happy to review PRs that add the missing browsers.

**Comment by kapros** [comment]
best I could find was [Desktop Safari for Webkit](https://github.com/microsoft/playwright/blob/a51c48fcb106c925b921cdfbfe546cde2523e416/packages/playwright-core/src/server/deviceDescriptorsSource.json#L1317), but not Opera. 
@AptecoJoe would you mind providing an example of how you were able to launch Opera with Playwright?

**Comment by kapros** [comment]
On top that, using Safari from the above link is, I believe, going to require passing in a BrowserNewContextOptions object to the IBrowserContext (which comes from IBrowser) when creating a new context, which is not very compatible with the current design.
